// TODO: Create a function that returns a license badge based on which license is passed in
// If there is no license, return an empty string

// TODO: Create a function that returns the license link
// If there is no license, return an empty string
function renderLicenseLink(license) {
  return `https://img.shields.io/badge/license-${license}-brightgreen`;
}

// TODO: Create a function that returns the license section of README
// If there is no license, return an empty string
function renderLicenseSection(license) {
  return `![badge](${renderLicenseLink(license)})`;
}

// TODO: Create a function to generate markdown for README

function generateMarkdown(data) {
  const markdownFormat = `
  <h1 align="center">${data.title}</h1>
    
  ![badge](https://img.shields.io/badge/license-${
    data.license
  }-brightgreen)<br />
  ## Description
     ${data.description}
  ## Table of Contents
  - [Description](#description)
  - [Installation](#installation)
  - [Usage](#usage)
  - [License](#license)
  - [Contributing](#contributing)
  - [Tests](#tests)
  - [Questions](#questions)
  ## Installation
     ${data.installation}
  ## Usage
     ${data.usage}
  ## License
  ${renderLicenseSection(data.license)}
  <br />
  This application is legally covered by the ${data.license} license. 
  ## Contributing
     ${data.contributing}
  ## Tests
     ${data.tests}
  ## Questions
     ${data.questions}<br />
  <br />
    If you need to contact me you can reach me on GitHub: [sensational11](https://github.com/sensational11)<br />
  <br />
     If You can reach me with additional questions contact me at: mackn478@gmail.com <br /><br />
     This README was generated by [README-generator](https://github.com/sensational11/Professional-Read-Me)
      `;

  return markdownFormat;
}

module.exports = generateMarkdown;
